name: pathika
description: A new Flutter project.

version: 1.0.8+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  devicelocale: ^0.6.0
  dio: ^5.1.2
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_logging_interceptor: ^1.0.1
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cupertino_settings: ^0.5.0
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  google_mobile_ads: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  meta: ^1.8.0
  path_provider: ^2.0.12
  platform_widget_mixin: ^0.0.1
  retrofit: ^4.0.1
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  universal_io: ^2.0.4
  url_launcher: ^6.1.8

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^4.0.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.0
  retrofit_generator: ^6.0.0+3

dependency_overrides:
  dio: ^5.1.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets_remote/assets/json/v1/languages.json
