name: pathika
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+2
  path_provider: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/details.json
    - assets/data/languages.json
    - assets/data/places.json
    
    
    
    
    
    
    
    
    